// @generated by oxisport-codegen. Do not edit manually.
// source: specs/intervals/intervals.yaml
// generator: oxisport-codegen v0.1.0

#![allow(clippy::all)]
#![allow(dead_code)]
#![allow(missing_docs)]

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AthleteResponse {
    pub id: u64,
    #[serde(default)]
    pub first_name: Option<String>,
    #[serde(default)]
    pub last_name: Option<String>,
    #[serde(default)]
    pub display_name: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ActivitySummary {
    pub id: String,
    #[serde(default)]
    pub name: Option<String>,
    pub r#type: String,
    pub start_date_local: String,
    #[serde(default)]
    pub distance: Option<f64>,
    #[serde(default)]
    pub moving_time: Option<u32>,
    #[serde(default)]
    pub elapsed_time: Option<u32>,
    #[serde(default)]
    pub average_heartrate: Option<f64>,
    #[serde(default)]
    pub average_watts: Option<f64>,
    #[serde(default)]
    pub average_cadence: Option<f64>,
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct ListActivitiesQuery {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub oldest: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub newest: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<u32>,
}

#[derive(Debug, Clone)]
pub struct IntervalsClient {
    pub(crate) client: oxisport_runtime::Client,
    pub(crate) base_url: url::Url,
}

impl IntervalsClient {
    /// Creates a client for the `intervals` service.
    pub fn new(client: oxisport_runtime::Client, base_url: url::Url) -> Self {
        Self { client, base_url }
    }

    /// Executes `GET /athlete/{id}`.
    pub async fn get_athlete(
        &self,
        id: u64,
    ) -> std::result::Result<AthleteResponse, oxisport_core::Error> {
        let path = format!(
            "/athlete/{id}",
            id = oxisport_runtime::util::encode_path_segment(&id.to_string())
        );
        let url = self.base_url.join(&path).map_err(|e| {
            oxisport_core::Error::invalid_request(format!("invalid request URL: {e}"))
        })?;
        let request = self
            .client
            .request(oxisport_runtime::http::Method::GET, url);
        let response = request
            .send()
            .await
            .map_err(|e| e.with_provider("intervals"))?;
        response.json().await
    }

    /// Executes `GET /athlete/{id}/activities`.
    pub async fn list_activities(
        &self,
        id: u64,
        oldest: Option<&str>,
        newest: Option<&str>,
        limit: Option<u32>,
    ) -> std::result::Result<Vec<ActivitySummary>, oxisport_core::Error> {
        let path = format!(
            "/athlete/{id}/activities",
            id = oxisport_runtime::util::encode_path_segment(&id.to_string())
        );
        let url = self.base_url.join(&path).map_err(|e| {
            oxisport_core::Error::invalid_request(format!("invalid request URL: {e}"))
        })?;
        let request = self
            .client
            .request(oxisport_runtime::http::Method::GET, url);
        let query = ListActivitiesQuery {
            oldest: oldest.map(Into::into),
            newest: newest.map(Into::into),
            limit: limit.map(Into::into),
        };
        let request = request.query(&query);
        let response = request
            .send()
            .await
            .map_err(|e| e.with_provider("intervals"))?;
        response.json().await
    }

    /// Executes `GET /activity/{id}`.
    pub async fn get_activity(
        &self,
        id: &str,
    ) -> std::result::Result<ActivitySummary, oxisport_core::Error> {
        let path = format!(
            "/activity/{id}",
            id = oxisport_runtime::util::encode_path_segment(&id.to_string())
        );
        let url = self.base_url.join(&path).map_err(|e| {
            oxisport_core::Error::invalid_request(format!("invalid request URL: {e}"))
        })?;
        let request = self
            .client
            .request(oxisport_runtime::http::Method::GET, url);
        let response = request
            .send()
            .await
            .map_err(|e| e.with_provider("intervals"))?;
        response.json().await
    }
}
