// @generated by oxisport-codegen. Do not edit manually.
// source: specs/examples/example.yaml
// generator: oxisport-codegen v0.1.0

#![allow(clippy::all)]
#![allow(dead_code)]
#![allow(missing_docs)]

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ActivityResponse {
    pub id: String,
    #[serde(default)]
    pub name: Option<String>,
    pub sport: String,
    pub start_time: String,
    pub distance_meters: u64,
    pub duration_seconds: u64,
    #[serde(default)]
    pub average_heart_rate: Option<u16>,
    #[serde(default)]
    pub average_power: Option<u16>,
    #[serde(default)]
    pub average_cadence: Option<u16>,
}

#[derive(Debug, Clone)]
pub struct ExampleClient {
    pub(crate) client: oxisport_runtime::Client,
    pub(crate) base_url: url::Url,
}

impl ExampleClient {
    /// Creates a client for the `example` service.
    pub fn new(client: oxisport_runtime::Client, base_url: url::Url) -> Self {
        Self { client, base_url }
    }

    /// Executes `GET /activities/{id}`.
    pub async fn get_activity(
        &self,
        id: &str,
    ) -> std::result::Result<ActivityResponse, oxisport_core::Error> {
        let path = format!(
            "/activities/{id}",
            id = oxisport_runtime::util::encode_path_segment(&id.to_string())
        );
        let url = self.base_url.join(&path).map_err(|e| {
            oxisport_core::Error::invalid_request(format!("invalid request URL: {e}"))
        })?;
        let request = self
            .client
            .request(oxisport_runtime::http::Method::GET, url);
        let response = request
            .send()
            .await
            .map_err(|e| e.with_provider("example"))?;
        response.json().await
    }

    /// Executes `GET /activities`.
    pub async fn list_activities(
        &self,
    ) -> std::result::Result<Vec<ActivityResponse>, oxisport_core::Error> {
        let path = "/activities";
        let url = self.base_url.join(&path).map_err(|e| {
            oxisport_core::Error::invalid_request(format!("invalid request URL: {e}"))
        })?;
        let request = self
            .client
            .request(oxisport_runtime::http::Method::GET, url);
        let response = request
            .send()
            .await
            .map_err(|e| e.with_provider("example"))?;
        response.json().await
    }
}
