//! Rust source generation from the internal IR.

use std::fmt::Write;

use crate::ir::{Api, Endpoint, FieldDef, WireType};

/// Writes a line into a `String`; cannot fail, so the `fmt::Error` is
/// discarded.
macro_rules! wln {
    ($out:expr) => {
        writeln!($out).expect("writing to a String cannot fail")
    };
    ($out:expr, $($arg:tt)*) => {
        writeln!($out, $($arg)*).expect("writing to a String cannot fail")
    };
}

/// Generates the raw client source for an API.
///
/// `source` is the spec path and `generator_version` the codegen version;
/// both are embedded in the header for traceability.
pub fn generate(api: &Api, source: &str, generator_version: &str) -> String {
    let client_name = format!("{}Client", upper_camel(&api.service));
    let mut out = String::new();

    wln!(
        out,
        "// @generated by oxisport-codegen. Do not edit manually."
    );
    wln!(out, "// source: {source}");
    wln!(out, "// generator: oxisport-codegen v{generator_version}");
    wln!(out);
    wln!(out, "#![allow(clippy::all)]");
    wln!(out, "#![allow(dead_code)]");
    wln!(out, "#![allow(missing_docs)]");
    wln!(out);
    wln!(out, "use serde::{{Deserialize, Serialize}};");
    wln!(out);

    for ty in &api.types {
        emit_struct(&mut out, ty);
        wln!(out);
    }

    for endpoint in &api.endpoints {
        emit_query_struct(&mut out, endpoint);
    }

    emit_client(&mut out, &client_name, &api.service, api);
    out
}

fn emit_struct(out: &mut String, ty: &crate::ir::TypeDef) {
    wln!(
        out,
        "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]"
    );
    wln!(out, "pub struct {} {{", ty.name);
    for field in &ty.fields {
        if field.optional {
            wln!(out, "    #[serde(default)]");
        }
        wln!(
            out,
            "    pub {}: {},",
            rust_ident(&field.name),
            field_type(field)
        );
    }
    wln!(out, "}}");
}

fn emit_client(out: &mut String, client_name: &str, service: &str, api: &Api) {
    wln!(out, "#[derive(Debug, Clone)]");
    wln!(out, "pub struct {client_name} {{");
    wln!(out, "    pub(crate) client: oxisport_runtime::Client,");
    wln!(out, "    pub(crate) base_url: url::Url,");
    wln!(out, "}}");
    wln!(out);
    wln!(out, "impl {client_name} {{");
    wln!(out, "    /// Creates a client for the `{service}` service.");
    wln!(
        out,
        "    pub fn new(client: oxisport_runtime::Client, base_url: url::Url) -> Self {{"
    );
    wln!(out, "        Self {{ client, base_url }}");
    wln!(out, "    }}");
    wln!(out);

    for endpoint in &api.endpoints {
        emit_endpoint(out, service, endpoint);
        wln!(out);
    }
    wln!(out, "}}");
}

fn emit_endpoint(out: &mut String, service: &str, endpoint: &Endpoint) {
    let method = endpoint.method.as_str();
    let response_type = endpoint
        .response
        .as_ref()
        .map(rust_type)
        .unwrap_or_else(|| "()".to_string());
    let mut params: Vec<String> = endpoint
        .path_params
        .iter()
        .map(|p| format!("{}: {}", p.name, path_param_type(p)))
        .collect();
    for p in &endpoint.query_params {
        params.push(format!("{}: {}", p.name, query_param_type(p)));
    }
    let params = if params.is_empty() {
        String::new()
    } else {
        format!(", {}", params.join(", "))
    };
    let query_struct = query_struct_name(&endpoint.name);

    wln!(
        out,
        "    /// Executes `{method} {path}`.",
        path = endpoint.path
    );
    wln!(
        out,
        "    pub async fn {}(&self{params}) -> std::result::Result<{response_type}, oxisport_core::Error> {{",
        endpoint.name,
    );

    let request_path = endpoint.path.strip_prefix('/').unwrap_or(&endpoint.path);
    if endpoint.path_params.is_empty() {
        wln!(out, "        let path = {:?};", request_path);
    } else {
        let args = endpoint
            .path_params
            .iter()
            .map(|p| {
                format!(
                    "{} = oxisport_runtime::util::encode_path_segment(&{}.to_string())",
                    p.name, p.name
                )
            })
            .collect::<Vec<_>>()
            .join(", ");
        wln!(
            out,
            "        let path = format!({:?}, {args});",
            request_path
        );
    }
    wln!(
        out,
        "        let url = self.base_url.join(&path).map_err(|e| oxisport_core::Error::invalid_request(format!(\"invalid request URL: {{e}}\")))?;"
    );
    wln!(
        out,
        "        let request = self.client.request(oxisport_runtime::http::Method::{method}, url);"
    );
    if !endpoint.query_params.is_empty() {
        wln!(
            out,
            "        let query = {query_struct} {{ {} }};",
            endpoint
                .query_params
                .iter()
                .map(|p| format!("{}: {}", p.name, query_field_init(p)))
                .collect::<Vec<_>>()
                .join(", ")
        );
        wln!(out, "        let request = request.query(&query);");
    }
    wln!(
        out,
        "        let response = request.send().await.map_err(|e| e.with_provider({service:?}))?;"
    );
    if endpoint.response.is_some() {
        wln!(out, "        response.json().await");
    } else {
        wln!(out, "        response.bytes().await?;");
        wln!(out, "        Ok(())");
    }
    wln!(out, "    }}");
}

/// Emits a serializable query struct for an endpoint with query parameters.
fn emit_query_struct(out: &mut String, endpoint: &Endpoint) {
    if endpoint.query_params.is_empty() {
        return;
    }
    let name = query_struct_name(&endpoint.name);
    wln!(out, "#[derive(Debug, Clone, serde::Serialize)]");
    wln!(out, "pub struct {name} {{");
    for param in &endpoint.query_params {
        if param.optional {
            wln!(
                out,
                "    #[serde(skip_serializing_if = \"Option::is_none\")]"
            );
        }
        let base = rust_type(&param.ty);
        let ty = if param.optional {
            format!("Option<{base}>")
        } else {
            base
        };
        wln!(out, "    pub {}: {},", rust_ident(&param.name), ty);
    }
    wln!(out, "}}");
    wln!(out);
}

fn query_struct_name(endpoint_name: &str) -> String {
    let mut parts = endpoint_name.split('_').peekable();
    let mut out = String::new();
    for part in parts.by_ref() {
        if !part.is_empty() {
            out.push_str(&upper_camel(part));
        }
    }
    if out.is_empty() {
        out.push_str("Query");
    }
    format!("{out}Query")
}

fn path_param_type(field: &FieldDef) -> String {
    if field.ty == WireType::String {
        "&str".to_string()
    } else {
        rust_type(&field.ty)
    }
}

fn query_param_type(field: &FieldDef) -> String {
    let base = if field.ty == WireType::String {
        "&str".to_string()
    } else {
        rust_type(&field.ty)
    };
    if field.optional {
        format!("Option<{base}>")
    } else {
        base
    }
}

/// Expression converting a function argument into the query struct field.
fn query_field_init(field: &FieldDef) -> String {
    if field.optional {
        format!("{}.map(Into::into)", field.name)
    } else {
        format!("{}.into()", field.name)
    }
}

fn field_type(field: &FieldDef) -> String {
    let base = rust_type(&field.ty);
    if field.optional {
        format!("Option<{base}>")
    } else {
        base
    }
}

fn rust_type(ty: &WireType) -> String {
    match ty {
        WireType::String => "String".to_string(),
        WireType::Bool => "bool".to_string(),
        WireType::I16 => "i16".to_string(),
        WireType::I32 => "i32".to_string(),
        WireType::I64 => "i64".to_string(),
        WireType::U16 => "u16".to_string(),
        WireType::U32 => "u32".to_string(),
        WireType::U64 => "u64".to_string(),
        WireType::F32 => "f32".to_string(),
        WireType::F64 => "f64".to_string(),
        WireType::Json => "serde_json::Value".to_string(),
        WireType::List(inner) => format!("Vec<{}>", rust_type(inner)),
        WireType::Model(name) => name.clone(),
    }
}

fn upper_camel(name: &str) -> String {
    let mut chars = name.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

/// Rust keywords that need raw-identifier escaping in field positions.
const RUST_KEYWORDS: &[&str] = &[
    "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn", "for",
    "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return",
    "self", "Self", "static", "struct", "super", "trait", "true", "type", "unsafe", "use", "where",
    "while", "async", "await", "dyn", "abstract", "become", "box", "do", "final", "macro",
    "override", "priv", "typeof", "unsized", "virtual", "yield", "try",
];

/// Returns the Rust identifier for a spec name, escaping keywords.
fn rust_ident(name: &str) -> String {
    if RUST_KEYWORDS.contains(&name) {
        format!("r#{name}")
    } else {
        name.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::generate;
    use crate::parse::parse;

    const SPEC: &str = r#"
service: example
base_url: https://example.invalid
types:
  - name: ActivityResponse
    fields:
      - name: id
        type: string
      - name: distance_meters
        type: uint64
        optional: true
endpoints:
  - name: get_activity
    method: GET
    path: /activities/{id}
    path_params:
      - name: id
        type: string
    response: ActivityResponse
  - name: list_activities
    method: GET
    path: /activities
    query_params:
      - name: oldest
        type: string
        optional: true
      - name: limit
        type: uint32
    response: list<ActivityResponse>
  - name: ping
    method: HEAD
    path: /ping
"#;

    fn code() -> String {
        let api = parse(SPEC).expect("spec parses");
        generate(&api, "specs/examples/example.yaml", "0.1.0")
    }

    #[test]
    fn generated_code_has_header_and_banner() {
        let code = code();
        assert!(code.starts_with("// @generated by oxisport-codegen. Do not edit manually.\n"));
        assert!(code.contains("// source: specs/examples/example.yaml"));
        assert!(code.contains("// generator: oxisport-codegen v0.1.0"));
        assert!(code.contains("#![allow(clippy::all)]"));
    }

    #[test]
    fn generated_code_contains_structs_and_client() {
        let code = code();
        assert!(code.contains("pub struct ActivityResponse {"));
        assert!(code.contains("pub id: String,"));
        assert!(code.contains("#[serde(default)]"));
        assert!(code.contains("pub distance_meters: Option<u64>,"));
        assert!(code.contains("pub struct ExampleClient {"));
        assert!(code.contains("pub async fn get_activity(&self, id: &str)"));
        assert!(code.contains("let path = format!(\"activities/{id}\", id = oxisport_runtime::util::encode_path_segment(&id.to_string()));"));
        assert!(code.contains("oxisport_runtime::http::Method::GET"));
        assert!(code.contains("e.with_provider(\"example\")"));
        assert!(
            code.contains("pub async fn list_activities(&self, oldest: Option<&str>, limit: u32)")
        );
        assert!(code.contains("pub struct ListActivitiesQuery {"));
        assert!(code.contains("#[serde(skip_serializing_if = \"Option::is_none\")]"));
        assert!(code.contains("pub oldest: Option<String>,"));
        assert!(code.contains("pub limit: u32,"));
        assert!(code.contains("let query = ListActivitiesQuery { oldest: oldest.map(Into::into), limit: limit.into() };"));
        assert!(code.contains("let request = request.query(&query);"));
        assert!(code.contains("pub async fn ping(&self)"));
    }

    #[test]
    fn generation_is_deterministic() {
        assert_eq!(code(), code());
    }
}
