//! Rust source generation from the internal IR.

use std::fmt::Write;

use crate::ir::{Api, Endpoint, FieldDef, WireType};

/// Writes a line into a `String`; cannot fail, so the `fmt::Error` is
/// discarded.
macro_rules! wln {
    ($out:expr) => {
        writeln!($out).expect("writing to a String cannot fail")
    };
    ($out:expr, $($arg:tt)*) => {
        writeln!($out, $($arg)*).expect("writing to a String cannot fail")
    };
}

/// Generates the raw client source for an API.
///
/// `source` is the spec path and `generator_version` the codegen version;
/// both are embedded in the header for traceability.
pub fn generate(api: &Api, source: &str, generator_version: &str) -> String {
    let client_name = format!("{}Client", upper_camel(&api.service));
    let mut out = String::new();

    wln!(
        out,
        "// @generated by oxisport-codegen. Do not edit manually."
    );
    wln!(out, "// source: {source}");
    wln!(out, "// generator: oxisport-codegen v{generator_version}");
    wln!(out);
    wln!(out, "#![allow(clippy::all)]");
    wln!(out, "#![allow(dead_code)]");
    wln!(out, "#![allow(missing_docs)]");
    wln!(out);
    wln!(out, "use serde::{{Deserialize, Serialize}};");
    wln!(out);

    for ty in &api.types {
        emit_struct(&mut out, ty);
        wln!(out);
    }

    emit_client(&mut out, &client_name, &api.service, api);
    out
}

fn emit_struct(out: &mut String, ty: &crate::ir::TypeDef) {
    wln!(
        out,
        "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]"
    );
    wln!(out, "pub struct {} {{", ty.name);
    for field in &ty.fields {
        if field.optional {
            wln!(out, "    #[serde(default)]");
        }
        wln!(out, "    pub {}: {},", field.name, field_type(field));
    }
    wln!(out, "}}");
}

fn emit_client(out: &mut String, client_name: &str, service: &str, api: &Api) {
    wln!(out, "#[derive(Debug, Clone)]");
    wln!(out, "pub struct {client_name} {{");
    wln!(out, "    client: oxisport_runtime::Client,");
    wln!(out, "    base_url: url::Url,");
    wln!(out, "}}");
    wln!(out);
    wln!(out, "impl {client_name} {{");
    wln!(out, "    /// Creates a client for the `{service}` service.");
    wln!(
        out,
        "    pub fn new(client: oxisport_runtime::Client, base_url: url::Url) -> Self {{"
    );
    wln!(out, "        Self {{ client, base_url }}");
    wln!(out, "    }}");
    wln!(out);

    for endpoint in &api.endpoints {
        emit_endpoint(out, service, endpoint);
        wln!(out);
    }
    wln!(out, "}}");
}

fn emit_endpoint(out: &mut String, service: &str, endpoint: &Endpoint) {
    let method = endpoint.method.as_str();
    let response_type = endpoint
        .response
        .as_ref()
        .map(rust_type)
        .unwrap_or_else(|| "()".to_string());
    let params = if endpoint.path_params.is_empty() {
        String::new()
    } else {
        let joined = endpoint
            .path_params
            .iter()
            .map(|p| format!("{}: {}", p.name, path_param_type(p)))
            .collect::<Vec<_>>()
            .join(", ");
        format!(", {joined}")
    };

    wln!(
        out,
        "    /// Executes `{method} {path}`.",
        path = endpoint.path
    );
    wln!(
        out,
        "    pub async fn {}(&self{params}) -> std::result::Result<{response_type}, oxisport_core::Error> {{",
        endpoint.name,
    );

    if endpoint.path_params.is_empty() {
        wln!(out, "        let path = {:?};", endpoint.path);
    } else {
        let args = endpoint
            .path_params
            .iter()
            .map(|p| {
                format!(
                    "{} = oxisport_runtime::util::encode_path_segment(&{}.to_string())",
                    p.name, p.name
                )
            })
            .collect::<Vec<_>>()
            .join(", ");
        wln!(
            out,
            "        let path = format!({:?}, {args});",
            endpoint.path
        );
    }
    wln!(
        out,
        "        let url = self.base_url.join(&path).map_err(|e| oxisport_core::Error::invalid_request(format!(\"invalid request URL: {{e}}\")))?;"
    );
    wln!(
        out,
        "        let response = self.client.request(oxisport_runtime::http::Method::{method}, url).send().await.map_err(|e| e.with_provider({service:?}))?;"
    );
    if endpoint.response.is_some() {
        wln!(out, "        response.json().await");
    } else {
        wln!(out, "        response.bytes().await?;");
        wln!(out, "        Ok(())");
    }
    wln!(out, "    }}");
}

fn path_param_type(field: &FieldDef) -> String {
    if field.ty == WireType::String {
        "&str".to_string()
    } else {
        rust_type(&field.ty)
    }
}

fn field_type(field: &FieldDef) -> String {
    let base = rust_type(&field.ty);
    if field.optional {
        format!("Option<{base}>")
    } else {
        base
    }
}

fn rust_type(ty: &WireType) -> String {
    match ty {
        WireType::String => "String".to_string(),
        WireType::Bool => "bool".to_string(),
        WireType::I16 => "i16".to_string(),
        WireType::I32 => "i32".to_string(),
        WireType::I64 => "i64".to_string(),
        WireType::U16 => "u16".to_string(),
        WireType::U32 => "u32".to_string(),
        WireType::U64 => "u64".to_string(),
        WireType::F32 => "f32".to_string(),
        WireType::F64 => "f64".to_string(),
        WireType::Json => "serde_json::Value".to_string(),
        WireType::List(inner) => format!("Vec<{}>", rust_type(inner)),
        WireType::Model(name) => name.clone(),
    }
}

fn upper_camel(name: &str) -> String {
    let mut chars = name.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::generate;
    use crate::parse::parse;

    const SPEC: &str = r#"
service: example
base_url: https://example.invalid
types:
  - name: ActivityResponse
    fields:
      - name: id
        type: string
      - name: distance_meters
        type: uint64
        optional: true
endpoints:
  - name: get_activity
    method: GET
    path: /activities/{id}
    path_params:
      - name: id
        type: string
    response: ActivityResponse
  - name: list_activities
    method: GET
    path: /activities
    response: list<ActivityResponse>
  - name: ping
    method: HEAD
    path: /ping
"#;

    fn code() -> String {
        let api = parse(SPEC).expect("spec parses");
        generate(&api, "specs/examples/example.yaml", "0.1.0")
    }

    #[test]
    fn generated_code_has_header_and_banner() {
        let code = code();
        assert!(code.starts_with("// @generated by oxisport-codegen. Do not edit manually.\n"));
        assert!(code.contains("// source: specs/examples/example.yaml"));
        assert!(code.contains("// generator: oxisport-codegen v0.1.0"));
        assert!(code.contains("#![allow(clippy::all)]"));
    }

    #[test]
    fn generated_code_contains_structs_and_client() {
        let code = code();
        assert!(code.contains("pub struct ActivityResponse {"));
        assert!(code.contains("pub id: String,"));
        assert!(code.contains("#[serde(default)]"));
        assert!(code.contains("pub distance_meters: Option<u64>,"));
        assert!(code.contains("pub struct ExampleClient {"));
        assert!(code.contains("pub async fn get_activity(&self, id: &str)"));
        assert!(code.contains("let path = format!(\"/activities/{id}\", id = oxisport_runtime::util::encode_path_segment(&id.to_string()));"));
        assert!(code.contains("oxisport_runtime::http::Method::GET"));
        assert!(code.contains("e.with_provider(\"example\")"));
        assert!(code.contains("pub async fn list_activities(&self)"));
        assert!(code.contains("pub async fn ping(&self)"));
    }

    #[test]
    fn generation_is_deterministic() {
        assert_eq!(code(), code());
    }
}
