//! Raw client code generation for OxiSport providers.
//!
//! Codegen targets only raw provider APIs, below the provider adapter
//! boundary. It never generates `oxisport-core` domain types, capability
//! implementations or cross-provider workflows.
//!
//! Pipeline:
//!
//! ```text
//! custom YAML spec -> internal IR -> Rust raw client source
//! ```
//!
//! Generated sources are committed to git and never run from `build.rs`.
//! The format is intentionally minimal for now; the IR is designed so an
//! OpenAPI frontend can be added later.
//!
//! TODO: query parameters, headers, shared request/response models.

pub mod generator;
pub mod ir;
pub mod parse;

pub use generator::generate;
pub use parse::{Error, Result, parse};

/// Marker every generated file starts with.
pub const GENERATED_HEADER: &str = "// @generated by oxisport-codegen. Do not edit manually.";

/// Parses a YAML spec and generates the Rust raw client source.
///
/// `source` is the spec file path, embedded in the generated header for
/// traceability.
pub fn codegen_from_yaml(yaml: &str, source: &str) -> Result<String> {
    let api = parse(yaml)?;
    Ok(generate(&api, source, env!("CARGO_PKG_VERSION")))
}
